"""
Realistic mock tweet data for demo mode.
All timestamps are generated dynamically so the data always looks current.

Two monitoring tiers:
  Tier 1 — AI YouTubers (Früh-Signale für Video-Adaptionen)
  Tier 2 — AI Research & Industry Accounts
"""

from datetime import datetime, timedelta, timezone


def _ago(hours=0, minutes=0):
    """Return an ISO timestamp for N hours/minutes ago."""
    dt = datetime.now(timezone.utc) - timedelta(hours=hours, minutes=minutes)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


# ═══════════════════════════════════════════════════════════════════════════════
# TIER 1 — AI-YOUTUBER FRÜH-SIGNALE
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_TWEETS = [
    {
        "id": "yt001",
        "author": "nateherk",
        "text": "Working on a big video about agentic AI workflows. The shift from 'ask AI a question' to 'give AI a whole project' is happening faster than most realize. Which tools are you actually using day-to-day for this? (n8n, Make, Cursor, custom?)",
        "likes": 1840,
        "retweets": 410,
        "replies": 520,
        "posted_at": _ago(hours=2, minutes=30),
        "url": "https://twitter.com/nateherk/status/yt001",
        "category": "youtube_signal",
        "adaptation": {
            "original_format": "How-to / Workflow-Video: '5 Agentic AI Workflows That Actually Work in 2025'",
            "german_title": "\"5 KI-Agenten-Workflows, die 2025 wirklich funktionieren\" oder \"So delegierst du ganze Projekte an KI\"",
            "audience_fit": "Unternehmer, Freelancer, Content Creators (25–45 J.) die produktiver werden wollen — sehr hohe Relevanz für deutschsprachige Creator",
            "hook": "\"Die meisten nutzen KI noch wie eine bessere Suchmaschine. Das hier ist der Unterschied zwischen ChatGPT-User und KI-Power-User.\"",
            "thumbnail": "Split-Screen: Überarbeiteter Mann am Laptop (❌) vs. entspannter Creator schaut zu wie KI-Dashboard läuft (✅) — Text: 'So arbeiten Top-Creator 2025'",
            "struktur": "1. Intro: warum KI-Chats veraltet sind | 2. Was ist ein Agent? (einfache Analogie) | 3. Tool-Demo: n8n oder Make | 4. Drei konkrete Workflows live zeigen | 5. CTA: Welchen Workflow soll ich als nächstes zeigen?",
        },
    },
    {
        "id": "yt002",
        "author": "jackrobertsbiz",
        "text": "Hot take: in 18 months, every solo creator will have a full AI 'team' handling research, scripting, thumbnails and distribution. The ones building these systems NOW will be untouchable. Thread on what this actually looks like 🧵",
        "likes": 3200,
        "retweets": 890,
        "replies": 640,
        "posted_at": _ago(hours=4, minutes=10),
        "url": "https://twitter.com/jackrobertsbiz/status/yt002",
        "category": "youtube_signal",
        "adaptation": {
            "original_format": "Meinungs-/Predictions-Video: 'The Solo Creator AI Stack 2026 — What Top YouTubers Will Run'",
            "german_title": "\"Dein KI-Team als Solo-Creator — was Top-YouTuber 2026 nutzen werden\" oder \"Warum Solo-Creator, die KI ignorieren, verlieren\"",
            "audience_fit": "Ambitionierte deutschsprachige YouTuber & Creator (18–35 J.) die ihren Kanal skalieren wollen — HOHER Trend-Fit",
            "hook": "\"In 18 Monaten haben die besten Creators kein Team aus Menschen mehr — sie haben ein KI-Team. Wer das jetzt aufbaut, ist unschlagbar.\"",
            "thumbnail": "Creator von vorne + 4 kleine KI-Icons um ihn herum (Research / Script / Thumbnail / Distribution) — Text: 'Dein KI-Team 2026'",
            "struktur": "1. Zukunfts-Szenario malen | 2. Aktuell: was braucht ein Creator-Team? | 3. KI-Equivalents für jeden Job | 4. Stack vorstellen (Claude/Perplexity/Midjourney/n8n) | 5. Jetzt starten — 30-Tage-Challenge",
        },
    },
    {
        "id": "yt003",
        "author": "gregisenberg",
        "text": "I've been quietly testing 12 different AI tools for building internet businesses for 3 months. Some are game-changers. Most are noise. Sharing the full breakdown this week — DM me 'AI STACK' and I'll send it when it's live.",
        "likes": 5100,
        "retweets": 1200,
        "replies": 980,
        "posted_at": _ago(hours=1, minutes=45),
        "url": "https://twitter.com/gregisenberg/status/yt003",
        "category": "youtube_signal",
        "adaptation": {
            "original_format": "Review / Ranking-Video: 'I Tested 12 AI Business Tools for 3 Months — Here's What Actually Works'",
            "german_title": "\"Ich habe 12 KI-Tools 3 Monate lang getestet — das ist mein ehrliches Urteil\" oder \"KI-Tools für Online-Business: Was funktioniert wirklich?\"",
            "audience_fit": "Online-Unternehmer, Side-Hustle-Interessierte, Digital Nomads (22–40 J.) — deutschsprachiger Markt hungert nach ehrlichen Tool-Reviews",
            "hook": "\"12 KI-Tools, 3 Monate, echtes Geld ausgegeben. Hier ist, was ich dir nicht verkaufen will — aber trotzdem sagen muss.\"",
            "thumbnail": "Grid mit 12 Tool-Logos, große rote X auf einigen, grüne Haken auf wenigen — Text: 'Der ehrliche Test' + Gesicht mit skeptischem Blick",
            "struktur": "1. Warum ich das gemacht habe | 2. Bewertungskriterien | 3. Tool-Durchgang: kurze Demos | 4. Gewinner & Verlierer | 5. Mein persönlicher Stack | 6. Was ich nächsten Monat teste",
        },
    },
    {
        "id": "yt004",
        "author": "TomSolidPM",
        "text": "Product managers who haven't deeply integrated AI into their workflow are going to be replaced — not by AI, but by PMs who have. The skill gap is widening fast. Next video: the actual PM AI toolkit for 2025.",
        "likes": 2600,
        "retweets": 720,
        "replies": 490,
        "posted_at": _ago(hours=6, minutes=0),
        "url": "https://twitter.com/TomSolidPM/status/yt004",
        "category": "youtube_signal",
        "adaptation": {
            "original_format": "Career / Productivity-Video: 'The PM AI Toolkit 2025 — Skills That Will Make You Irreplaceable'",
            "german_title": "\"Der KI-Toolkit für Product Manager 2025 — so bleibst du unersetzlich\" oder \"Welche Jobs KI wirklich bedroht (und wie du dich schützt)\"",
            "audience_fit": "Product Manager, UX Designer, Tech-Professionals (28–45 J.) — breiter anwendbar als nur PMs, gut für DACH-Business-Publikum",
            "hook": "\"Du wirst nicht von KI ersetzt. Du wirst von jemandem ersetzt, der KI besser nutzt als du. Hier ist die Lücke — und wie du sie schließt.\"",
            "thumbnail": "Zwei Personen: eine läuft vorwärts mit KI-Badge, eine steht still — Text: 'Wer wird ersetzt?' mit rotem Pfeil",
            "struktur": "1. Realitäts-Check: welche Jobs sind betroffen? | 2. Konkrete KI-Skills für PMs | 3. Tool-Demo: Claude für PRDs / Notion AI / Figma AI | 4. 30-Tage-Lernplan | 5. Community-Frage: welcher Beruf soll als nächstes?",
        },
    },
    {
        "id": "yt005",
        "author": "chaseai",
        "text": "The vibe coding era is over. We're entering the vibe *building* era. People aren't just generating code snippets anymore — they're shipping full products in a weekend with zero engineering background. I'm documenting this whole shift in my next video.",
        "likes": 4300,
        "retweets": 1050,
        "replies": 760,
        "posted_at": _ago(hours=3, minutes=55),
        "url": "https://twitter.com/chaseai/status/yt005",
        "category": "youtube_signal",
        "adaptation": {
            "original_format": "Trend / Inspire-Video: 'Vibe Building — How Non-Coders Are Shipping Real Products in 2025'",
            "german_title": "\"Vibe Building: Wie Nicht-Entwickler 2025 echte Produkte launchen\" oder \"In einem Wochenende zur fertigen App — ohne Programmierkenntisse\"",
            "audience_fit": "Gründer, Seiteneinsteiger, Kreative ohne Tech-Hintergrund (20–40 J.) — eines der heißesten Themen im deutschsprachigen Creator-Raum",
            "hook": "\"Kein Code. Kein Team. Ein Wochenende. Fertige App. Das ist 2025 — und die meisten Menschen haben das noch nicht realisiert.\"",
            "thumbnail": "Laptop-Screen mit App-Interface, daneben eine Stoppuhr mit '48h' — Text: 'Von 0 zur App' + überraschtes Gesicht",
            "struktur": "1. Was ist Vibe Building? | 2. Tools: Cursor / Bolt / Replit | 3. Live-Demo: einfache App in 30 Min | 4. Echte Beispiele von Gründern | 5. Grenzen & Risiken | 6. Wo anfangen?",
        },
    },
    {
        "id": "yt006",
        "author": "nateherk",
        "text": "Everyone keeps asking me about the best AI tools for content research. Honest answer: it's not about the tools, it's about the prompting framework. I've built a system that cuts my research time by 80%. Sharing the whole thing this week.",
        "likes": 2100,
        "retweets": 560,
        "replies": 430,
        "posted_at": _ago(hours=8, minutes=20),
        "url": "https://twitter.com/nateherk/status/yt006",
        "category": "youtube_signal",
        "adaptation": {
            "original_format": "Tutorial / Framework-Video: 'My AI Content Research System — 80% Faster, Same Quality'",
            "german_title": "\"Mein KI-Recherche-System: 80% weniger Zeit, gleiche Qualität\" oder \"Das Prompting-Framework, das meine Content-Recherche revolutioniert hat\"",
            "audience_fit": "YouTube Creator, Blogger, Journalisten, Marketer (22–40 J.) — sehr breiter Fit, Evergreen-Potential für deutschsprachigen Kanal",
            "hook": "\"Ich habe nicht einfach ChatGPT geöffnet. Ich habe ein System gebaut. Hier ist der Unterschied — und warum du ohne System 3x länger brauchst.\"",
            "thumbnail": "Uhr mit '80% weniger Zeit' + Notizbuch mit Haken — Text: 'Das KI-Recherche-System' + erklärendes Gesicht",
            "struktur": "1. Problem: schlechte KI-Recherche kostet Zeit | 2. Das Framework erklären | 3. Prompt-Templates live zeigen | 4. Vorher/Nachher Vergleich | 5. Download-Link Framework | 6. Welches Thema soll ich nächste Woche recherchieren?",
        },
    },

    # ═══════════════════════════════════════════════════════════════════════
    # TIER 2 — AI RESEARCH & INDUSTRY (bisherige Accounts)
    # ═══════════════════════════════════════════════════════════════════════

    # ── MODEL RELEASES ──────────────────────────────────────────────────────
    {
        "id": "m001",
        "author": "sama",
        "text": "big week. can't say more yet but you'll see tomorrow morning.",
        "likes": 22400,
        "retweets": 4800,
        "replies": 3100,
        "posted_at": _ago(hours=1, minutes=20),
        "url": "https://twitter.com/sama/status/m001",
        "category": "model_release",
    },
    {
        "id": "m002",
        "author": "OpenAI",
        "text": "Introducing GPT-5. Our most capable model yet — available in ChatGPT and via API today. Dramatically improved reasoning, coding, and multimodal understanding. Full blog post: openai.com/gpt-5",
        "likes": 15300,
        "retweets": 5200,
        "replies": 2800,
        "posted_at": _ago(hours=2, minutes=10),
        "url": "https://twitter.com/OpenAI/status/m002",
        "category": "model_release",
    },
    {
        "id": "m003",
        "author": "mistralai",
        "text": "Mixtral 8x22B weights are now live on HuggingFace. 141B total parameters, 39B active. Apache 2.0. Our best open model to date — try it now.",
        "likes": 5100,
        "retweets": 2300,
        "replies": 490,
        "posted_at": _ago(hours=3, minutes=5),
        "url": "https://twitter.com/mistralai/status/m003",
        "category": "model_release",
    },
    {
        "id": "m004",
        "author": "AnthropicAI",
        "text": "Introducing Claude 4 — our most capable model yet. Available now via API. 200k context window, improved reasoning, and new extended tool use capabilities. Try it today: anthropic.com/claude",
        "likes": 8420,
        "retweets": 3100,
        "replies": 890,
        "posted_at": _ago(hours=8, minutes=30),
        "url": "https://twitter.com/AnthropicAI/status/m004",
        "category": "model_release",
    },
    {
        "id": "m005",
        "author": "GoogleDeepMind",
        "text": "Gemini Ultra 2 is here. Our new flagship model achieves state-of-the-art on every major benchmark. Now live in Google One AI Premium. Read the technical report: deepmind.google/gemini2",
        "likes": 6300,
        "retweets": 2100,
        "replies": 720,
        "posted_at": _ago(hours=5, minutes=40),
        "url": "https://twitter.com/GoogleDeepMind/status/m005",
        "category": "model_release",
    },
    {
        "id": "m006",
        "author": "GoogleDeepMind",
        "text": "AlphaFold 4 can now predict protein-protein and protein-ligand interactions with atomic accuracy. This changes drug discovery. Open weights available on GitHub.",
        "likes": 4500,
        "retweets": 1600,
        "replies": 280,
        "posted_at": _ago(hours=18, minutes=0),
        "url": "https://twitter.com/GoogleDeepMind/status/m006",
        "category": "model_release",
    },

    # ── TOOLS & PRODUCTS ────────────────────────────────────────────────────
    {
        "id": "t001",
        "author": "OpenAI",
        "text": "New in the API: structured outputs now supported for all GPT-4o models. Define a JSON schema, get guaranteed valid JSON back. No more parsing hacks. Available today.",
        "likes": 4200,
        "retweets": 1800,
        "replies": 430,
        "posted_at": _ago(hours=4, minutes=0),
        "url": "https://twitter.com/OpenAI/status/t001",
        "category": "tool_product",
    },
    {
        "id": "t002",
        "author": "AnthropicAI",
        "text": "Claude.ai now has a Projects feature — persistent memory across conversations, shared team workspaces, and custom instructions per project. Build your AI workflow once, use it forever.",
        "likes": 3700,
        "retweets": 1200,
        "replies": 380,
        "posted_at": _ago(hours=7, minutes=10),
        "url": "https://twitter.com/AnthropicAI/status/t002",
        "category": "tool_product",
    },
    {
        "id": "t003",
        "author": "gdb",
        "text": "Launching Swarm: a lightweight agent orchestration framework. Minimal abstractions, maximum control. Routines + handoffs. MIT licensed. github.com/openai/swarm",
        "likes": 5600,
        "retweets": 2200,
        "replies": 610,
        "posted_at": _ago(hours=10, minutes=30),
        "url": "https://twitter.com/gdb/status/t003",
        "category": "tool_product",
    },
    {
        "id": "t004",
        "author": "sama",
        "text": "ChatGPT memory is now on by default for all Plus users. It remembers who you are and what you care about across every conversation. You can see and control everything it knows.",
        "likes": 9800,
        "retweets": 3400,
        "replies": 1200,
        "posted_at": _ago(hours=6, minutes=5),
        "url": "https://twitter.com/sama/status/t004",
        "category": "tool_product",
    },

    # ── RESEARCH PAPERS ─────────────────────────────────────────────────────
    {
        "id": "r001",
        "author": "karpathy",
        "text": "We trained a small transformer from scratch and documented every step. The resulting paper covers architecture choices, training stability tricks, and why batch norm doesn't work for LLMs. arxiv.org/abs/r002",
        "likes": 8100,
        "retweets": 2700,
        "replies": 480,
        "posted_at": _ago(hours=3, minutes=30),
        "url": "https://twitter.com/karpathy/status/r001",
        "category": "research_paper",
    },
    {
        "id": "r002",
        "author": "ylecun",
        "text": "Our new paper on Joint Embedding Predictive Architectures (JEPA) shows that predicting in abstract space beats pixel-level prediction. This is how world models should be built. Not next-token prediction. arxiv.org/abs/r003",
        "likes": 4900,
        "retweets": 1500,
        "replies": 820,
        "posted_at": _ago(hours=11, minutes=20),
        "url": "https://twitter.com/ylecun/status/r002",
        "category": "research_paper",
    },
    {
        "id": "r003",
        "author": "fchollet",
        "text": "ARC-AGI 2 is out. All existing frontier models plateau below 20%. The test is specifically designed to resist memorization. Full benchmark and evaluation code: github.com/fchollet/arc-agi2",
        "likes": 6700,
        "retweets": 2400,
        "replies": 940,
        "posted_at": _ago(hours=15, minutes=10),
        "url": "https://twitter.com/fchollet/status/r003",
        "category": "research_paper",
    },
    {
        "id": "r004",
        "author": "emollick",
        "text": "New study: in a randomized controlled trial with 758 consultants at BCG, those using GPT-4 completed 12% more tasks, 25% faster, and with 40% higher quality. The effect was largest for the *lowest* performers. arxiv.org/abs/r005",
        "likes": 12100,
        "retweets": 4300,
        "replies": 1100,
        "posted_at": _ago(hours=8, minutes=0),
        "url": "https://twitter.com/emollick/status/r004",
        "category": "research_paper",
    },

    # ── FUNDING & BUSINESS ──────────────────────────────────────────────────
    {
        "id": "f001",
        "author": "rohanpaul_ai",
        "text": "BREAKING: xAI raises $6B Series B at a $24B valuation. This gives Elon the war chest to compete directly with OpenAI and Anthropic on infrastructure. Grok 3 coming soon.",
        "likes": 5800,
        "retweets": 2100,
        "replies": 930,
        "posted_at": _ago(hours=6, minutes=30),
        "url": "https://twitter.com/rohanpaul_ai/status/f001",
        "category": "funding_business",
    },
    {
        "id": "f002",
        "author": "sama",
        "text": "OpenAI's annualized revenue has crossed $2B. From $0 to $2B ARR in 2 years. This is the fastest-growing software company in history.",
        "likes": 18500,
        "retweets": 5600,
        "replies": 2400,
        "posted_at": _ago(hours=19, minutes=30),
        "url": "https://twitter.com/sama/status/f002",
        "category": "funding_business",
    },
    {
        "id": "f003",
        "author": "DrJimFan",
        "text": "NVIDIA's AI-related revenue: $14.5B last quarter. To put that in perspective — that's more than the entire cloud market was 10 years ago. The GPU supercycle is just beginning.",
        "likes": 7200,
        "retweets": 2600,
        "replies": 580,
        "posted_at": _ago(hours=17, minutes=10),
        "url": "https://twitter.com/DrJimFan/status/f003",
        "category": "funding_business",
    },

    # ── VIRAL DEBATES ───────────────────────────────────────────────────────
    {
        "id": "v001",
        "author": "karpathy",
        "text": "the best way to understand transformers is still to implement one from scratch. nothing has changed here. all the blog posts in the world don't substitute for writing the code.",
        "likes": 12300,
        "retweets": 2800,
        "replies": 440,
        "posted_at": _ago(hours=2, minutes=40),
        "url": "https://twitter.com/karpathy/status/v001",
        "category": "viral_debate",
    },
    {
        "id": "v002",
        "author": "emollick",
        "text": "unpopular opinion: the AI hype is actually *understated*. Most people still haven't seriously used these tools for their actual work. When they do, the reaction is uniformly one of shock. We're in the early adopter phase of something that will affect literally everyone.",
        "likes": 9400,
        "retweets": 3200,
        "replies": 1800,
        "posted_at": _ago(hours=5, minutes=15),
        "url": "https://twitter.com/emollick/status/v002",
        "category": "viral_debate",
    },
    {
        "id": "v003",
        "author": "ylecun",
        "text": "I'll say it again: current LLMs cannot reason. They can pattern-match on reasoning-like text. There is a fundamental difference. We need architecture innovation, not just scale. The bitter lesson has limits.",
        "likes": 7600,
        "retweets": 2100,
        "replies": 2300,
        "posted_at": _ago(hours=9, minutes=0),
        "url": "https://twitter.com/ylecun/status/v003",
        "category": "viral_debate",
    },
    {
        "id": "v004",
        "author": "sama",
        "text": "hot take: we'll have AGI before we have reliable self-driving cars. the hard parts of driving are mostly physical and edge-case adversarial. the hard parts of intelligence are mostly solved.",
        "likes": 31000,
        "retweets": 7400,
        "replies": 5600,
        "posted_at": _ago(hours=4, minutes=20),
        "url": "https://twitter.com/sama/status/v004",
        "category": "viral_debate",
    },

    # ── BENCHMARKS & NUMBERS ────────────────────────────────────────────────
    {
        "id": "b001",
        "author": "_akhaliq",
        "text": "Updated LMSys chatbot arena leaderboard. Claude 4 has taken the #1 spot overall. GPT-5 second. Gemini Ultra 2 third. Full breakdown by category: lmsys.org/arena",
        "likes": 4100,
        "retweets": 1600,
        "replies": 380,
        "posted_at": _ago(hours=2, minutes=0),
        "url": "https://twitter.com/_akhaliq/status/b001",
        "category": "benchmark_numbers",
    },
    {
        "id": "b002",
        "author": "OpenAI",
        "text": "GPT-5 benchmark results: MMLU 92.3% (vs GPT-4's 86.4%), HumanEval 96.1% (vs 67%), MATH 87.4% (vs 52.9%). Full evals: openai.com/gpt-5-evals",
        "likes": 7800,
        "retweets": 2900,
        "replies": 920,
        "posted_at": _ago(hours=3, minutes=15),
        "url": "https://twitter.com/OpenAI/status/b002",
        "category": "benchmark_numbers",
    },
    {
        "id": "b003",
        "author": "AnthropicAI",
        "text": "Claude 4 on SWE-bench Verified: 72.0%. That's 20 points above the previous SOTA. We also score 89.4% on MMLU and 68% on ARC-AGI. Full technical report: anthropic.com/claude4-report",
        "likes": 5300,
        "retweets": 1900,
        "replies": 540,
        "posted_at": _ago(hours=6, minutes=45),
        "url": "https://twitter.com/AnthropicAI/status/b003",
        "category": "benchmark_numbers",
    },
    {
        "id": "b004",
        "author": "fchollet",
        "text": "ARC-AGI 2 scores: GPT-5: 18%, Claude 4: 21%, Gemini Ultra 2: 16%, o3-mini: 14%, Human average: 98%. These models are not AGI. The benchmark is working exactly as intended.",
        "likes": 8900,
        "retweets": 3300,
        "replies": 1600,
        "posted_at": _ago(hours=16, minutes=0),
        "url": "https://twitter.com/fchollet/status/b004",
        "category": "benchmark_numbers",
    },
]


def get_mock_tweets():
    """Return mock tweets with freshly computed timestamps (always current)."""
    return MOCK_TWEETS
