"""
Realistic mock tweet data for demo mode.
All timestamps are generated dynamically so the data always looks current.
"""

from datetime import datetime, timedelta, timezone


def _ago(hours=0, minutes=0):
    """Return an ISO timestamp for N hours/minutes ago."""
    dt = datetime.now(timezone.utc) - timedelta(hours=hours, minutes=minutes)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


MOCK_TWEETS = [
    # ── MODEL RELEASES ──────────────────────────────────────────────────────
    {
        "id": "m001",
        "author": "sama",
        "text": "big week. can't say more yet but you'll see tomorrow morning.",
        "likes": 22400,
        "retweets": 4800,
        "replies": 3100,
        "posted_at": _ago(hours=1, minutes=20),
        "url": "https://twitter.com/sama/status/m001",
        "category": "model_release",
    },
    {
        "id": "m002",
        "author": "OpenAI",
        "text": "Introducing GPT-5. Our most capable model yet — available in ChatGPT and via API today. Dramatically improved reasoning, coding, and multimodal understanding. Full blog post: openai.com/gpt-5",
        "likes": 15300,
        "retweets": 5200,
        "replies": 2800,
        "posted_at": _ago(hours=2, minutes=10),
        "url": "https://twitter.com/OpenAI/status/m002",
        "category": "model_release",
    },
    {
        "id": "m003",
        "author": "mistralai",
        "text": "Mixtral 8x22B weights are now live on HuggingFace. 141B total parameters, 39B active. Apache 2.0. Our best open model to date — try it now.",
        "likes": 5100,
        "retweets": 2300,
        "replies": 490,
        "posted_at": _ago(hours=3, minutes=5),
        "url": "https://twitter.com/mistralai/status/m003",
        "category": "model_release",
    },
    {
        "id": "m004",
        "author": "AnthropicAI",
        "text": "Introducing Claude 4 — our most capable model yet. Available now via API. 200k context window, improved reasoning, and new extended tool use capabilities. Try it today: anthropic.com/claude",
        "likes": 8420,
        "retweets": 3100,
        "replies": 890,
        "posted_at": _ago(hours=8, minutes=30),
        "url": "https://twitter.com/AnthropicAI/status/m004",
        "category": "model_release",
    },
    {
        "id": "m005",
        "author": "GoogleDeepMind",
        "text": "Gemini Ultra 2 is here. Our new flagship model achieves state-of-the-art on every major benchmark. Now live in Google One AI Premium. Read the technical report: deepmind.google/gemini2",
        "likes": 6300,
        "retweets": 2100,
        "replies": 720,
        "posted_at": _ago(hours=5, minutes=40),
        "url": "https://twitter.com/GoogleDeepMind/status/m005",
        "category": "model_release",
    },
    {
        "id": "m006",
        "author": "mistralai",
        "text": "Mistral Large 3 is out. Top-tier performance in reasoning, code, and multilingual tasks. Available on our API and La Plateforme. Context: 128k tokens.",
        "likes": 3200,
        "retweets": 1400,
        "replies": 310,
        "posted_at": _ago(hours=12, minutes=15),
        "url": "https://twitter.com/mistralai/status/m006",
        "category": "model_release",
    },
    {
        "id": "m007",
        "author": "GoogleDeepMind",
        "text": "AlphaFold 4 can now predict protein-protein and protein-ligand interactions with atomic accuracy. This changes drug discovery. Open weights available on GitHub.",
        "likes": 4500,
        "retweets": 1600,
        "replies": 280,
        "posted_at": _ago(hours=18, minutes=0),
        "url": "https://twitter.com/GoogleDeepMind/status/m007",
        "category": "model_release",
    },
    {
        "id": "m008",
        "author": "huggingface",
        "text": "SmolLM2-1.7B is now the best small open model on the web. Runs fully on-device, even in the browser. Try the demo right now — no GPU needed.",
        "likes": 2100,
        "retweets": 890,
        "replies": 195,
        "posted_at": _ago(hours=14, minutes=25),
        "url": "https://twitter.com/huggingface/status/m008",
        "category": "model_release",
    },

    # ── TOOLS & PRODUCTS ────────────────────────────────────────────────────
    {
        "id": "t001",
        "author": "OpenAI",
        "text": "New in the API: structured outputs now supported for all GPT-4o models. Define a JSON schema, get guaranteed valid JSON back. No more parsing hacks. Available today.",
        "likes": 4200,
        "retweets": 1800,
        "replies": 430,
        "posted_at": _ago(hours=4, minutes=0),
        "url": "https://twitter.com/OpenAI/status/t001",
        "category": "tool_product",
    },
    {
        "id": "t002",
        "author": "AnthropicAI",
        "text": "Claude.ai now has a Projects feature — persistent memory across conversations, shared team workspaces, and custom instructions per project. Build your AI workflow once, use it forever.",
        "likes": 3700,
        "retweets": 1200,
        "replies": 380,
        "posted_at": _ago(hours=7, minutes=10),
        "url": "https://twitter.com/AnthropicAI/status/t002",
        "category": "tool_product",
    },
    {
        "id": "t003",
        "author": "huggingface",
        "text": "Inference Endpoints just got a major update: auto-scaling to zero, faster cold starts, and support for all GGUF models. Deploy any model in 2 clicks.",
        "likes": 1900,
        "retweets": 780,
        "replies": 140,
        "posted_at": _ago(hours=9, minutes=50),
        "url": "https://twitter.com/huggingface/status/t003",
        "category": "tool_product",
    },
    {
        "id": "t004",
        "author": "gdb",
        "text": "Launching Swarm: a lightweight agent orchestration framework. Minimal abstractions, maximum control. Routines + handoffs. MIT licensed. github.com/openai/swarm",
        "likes": 5600,
        "retweets": 2200,
        "replies": 610,
        "posted_at": _ago(hours=10, minutes=30),
        "url": "https://twitter.com/gdb/status/t004",
        "category": "tool_product",
    },
    {
        "id": "t005",
        "author": "DrJimFan",
        "text": "NVIDIA NIM microservices now include a code interpreter. Drop in a Python sandbox in one API call. The infra is already there — just use it.",
        "likes": 2800,
        "retweets": 960,
        "replies": 200,
        "posted_at": _ago(hours=20, minutes=0),
        "url": "https://twitter.com/DrJimFan/status/t005",
        "category": "tool_product",
    },
    {
        "id": "t006",
        "author": "mistralai",
        "text": "Le Chat is now free for everyone — unlimited messages, image understanding, web search, and document upload. No waitlist. Start chatting: chat.mistral.ai",
        "likes": 3100,
        "retweets": 1050,
        "replies": 260,
        "posted_at": _ago(hours=16, minutes=40),
        "url": "https://twitter.com/mistralai/status/t006",
        "category": "tool_product",
    },
    {
        "id": "t007",
        "author": "sama",
        "text": "ChatGPT memory is now on by default for all Plus users. It remembers who you are and what you care about across every conversation. You can see and control everything it knows.",
        "likes": 9800,
        "retweets": 3400,
        "replies": 1200,
        "posted_at": _ago(hours=6, minutes=5),
        "url": "https://twitter.com/sama/status/t007",
        "category": "tool_product",
    },

    # ── RESEARCH PAPERS ─────────────────────────────────────────────────────
    {
        "id": "r001",
        "author": "_akhaliq",
        "text": "New paper: 'Large Language Models are Few-Shot Reasoners via Chain-of-Thought Prompting' — 540B PaLM with CoT achieves 74% on GSM8K vs 17% without. arxiv.org/abs/r001",
        "likes": 2300,
        "retweets": 980,
        "replies": 140,
        "posted_at": _ago(hours=1, minutes=45),
        "url": "https://twitter.com/_akhaliq/status/r001",
        "category": "research_paper",
    },
    {
        "id": "r002",
        "author": "karpathy",
        "text": "We trained a small transformer from scratch and documented every step. The resulting paper covers architecture choices, training stability tricks, and why batch norm doesn't work for LLMs. arxiv.org/abs/r002",
        "likes": 8100,
        "retweets": 2700,
        "replies": 480,
        "posted_at": _ago(hours=3, minutes=30),
        "url": "https://twitter.com/karpathy/status/r002",
        "category": "research_paper",
    },
    {
        "id": "r003",
        "author": "ylecun",
        "text": "Our new paper on Joint Embedding Predictive Architectures (JEPA) shows that predicting in abstract space beats pixel-level prediction. This is how world models should be built. Not next-token prediction. arxiv.org/abs/r003",
        "likes": 4900,
        "retweets": 1500,
        "replies": 820,
        "posted_at": _ago(hours=11, minutes=20),
        "url": "https://twitter.com/ylecun/status/r003",
        "category": "research_paper",
    },
    {
        "id": "r004",
        "author": "fchollet",
        "text": "ARC-AGI 2 is out. All existing frontier models plateau below 20%. The test is specifically designed to resist memorization. Full benchmark and evaluation code: github.com/fchollet/arc-agi2",
        "likes": 6700,
        "retweets": 2400,
        "replies": 940,
        "posted_at": _ago(hours=15, minutes=10),
        "url": "https://twitter.com/fchollet/status/r004",
        "category": "research_paper",
    },
    {
        "id": "r005",
        "author": "emollick",
        "text": "New study: in a randomized controlled trial with 758 consultants at BCG, those using GPT-4 completed 12% more tasks, 25% faster, and with 40% higher quality. The effect was largest for the *lowest* performers. arxiv.org/abs/r005",
        "likes": 12100,
        "retweets": 4300,
        "replies": 1100,
        "posted_at": _ago(hours=8, minutes=0),
        "url": "https://twitter.com/emollick/status/r005",
        "category": "research_paper",
    },
    {
        "id": "r006",
        "author": "_akhaliq",
        "text": "New from Google: 'Gemini 1.5 Pro Technical Report' — 1M token context, needle-in-a-haystack: >99% recall at 1M tokens. Multi-modal across text, audio, images, video. arxiv.org/abs/r006",
        "likes": 3400,
        "retweets": 1200,
        "replies": 210,
        "posted_at": _ago(hours=4, minutes=50),
        "url": "https://twitter.com/_akhaliq/status/r006",
        "category": "research_paper",
    },
    {
        "id": "r007",
        "author": "rohanpaul_ai",
        "text": "'Scaling Laws for Neural Language Models' — revisited with 2025 data. The compute-optimal frontier has shifted. Chinchilla scaling is now outdated. New paper shows token/parameter ratios need updating. arxiv.org/abs/r007",
        "likes": 2800,
        "retweets": 1100,
        "replies": 310,
        "posted_at": _ago(hours=13, minutes=0),
        "url": "https://twitter.com/rohanpaul_ai/status/r007",
        "category": "research_paper",
    },

    # ── FUNDING & BUSINESS ──────────────────────────────────────────────────
    {
        "id": "f001",
        "author": "rohanpaul_ai",
        "text": "BREAKING: xAI raises $6B Series B at a $24B valuation. This gives Elon the war chest to compete directly with OpenAI and Anthropic on infrastructure. Grok 3 coming soon.",
        "likes": 5800,
        "retweets": 2100,
        "replies": 930,
        "posted_at": _ago(hours=6, minutes=30),
        "url": "https://twitter.com/rohanpaul_ai/status/f001",
        "category": "funding_business",
    },
    {
        "id": "f002",
        "author": "AnthropicAI",
        "text": "Anthropic has secured $4B in additional investment from Amazon, bringing total funding to $7.3B. This accelerates our work on frontier safety research and Claude's capabilities.",
        "likes": 4100,
        "retweets": 1300,
        "replies": 420,
        "posted_at": _ago(hours=22, minutes=0),
        "url": "https://twitter.com/AnthropicAI/status/f002",
        "category": "funding_business",
    },
    {
        "id": "f003",
        "author": "sama",
        "text": "OpenAI's annualized revenue has crossed $2B. From $0 to $2B ARR in 2 years. This is the fastest-growing software company in history.",
        "likes": 18500,
        "retweets": 5600,
        "replies": 2400,
        "posted_at": _ago(hours=19, minutes=30),
        "url": "https://twitter.com/sama/status/f003",
        "category": "funding_business",
    },
    {
        "id": "f004",
        "author": "DrJimFan",
        "text": "NVIDIA's AI-related revenue: $14.5B last quarter. To put that in perspective — that's more than the entire cloud market was 10 years ago. The GPU supercycle is just beginning.",
        "likes": 7200,
        "retweets": 2600,
        "replies": 580,
        "posted_at": _ago(hours=17, minutes=10),
        "url": "https://twitter.com/DrJimFan/status/f004",
        "category": "funding_business",
    },
    {
        "id": "f005",
        "author": "scaling01",
        "text": "Mistral AI now valued at $6B after latest round. French AI company is the only credible European frontier lab. Raised €600M. This is a geopolitical bet as much as a product bet.",
        "likes": 2100,
        "retweets": 780,
        "replies": 210,
        "posted_at": _ago(hours=21, minutes=0),
        "url": "https://twitter.com/scaling01/status/f005",
        "category": "funding_business",
    },

    # ── VIRAL DEBATES ───────────────────────────────────────────────────────
    {
        "id": "v001",
        "author": "karpathy",
        "text": "the best way to understand transformers is still to implement one from scratch. nothing has changed here. all the blog posts in the world don't substitute for writing the code.",
        "likes": 12300,
        "retweets": 2800,
        "replies": 440,
        "posted_at": _ago(hours=2, minutes=40),
        "url": "https://twitter.com/karpathy/status/v001",
        "category": "viral_debate",
    },
    {
        "id": "v002",
        "author": "emollick",
        "text": "unpopular opinion: the AI hype is actually *understated*. Most people still haven't seriously used these tools for their actual work. When they do, the reaction is uniformly one of shock. We're in the early adopter phase of something that will affect literally everyone.",
        "likes": 9400,
        "retweets": 3200,
        "replies": 1800,
        "posted_at": _ago(hours=5, minutes=15),
        "url": "https://twitter.com/emollick/status/v002",
        "category": "viral_debate",
    },
    {
        "id": "v003",
        "author": "ylecun",
        "text": "I'll say it again: current LLMs cannot reason. They can pattern-match on reasoning-like text. There is a fundamental difference. We need architecture innovation, not just scale. The bitter lesson has limits.",
        "likes": 7600,
        "retweets": 2100,
        "replies": 2300,
        "posted_at": _ago(hours=9, minutes=0),
        "url": "https://twitter.com/ylecun/status/v003",
        "category": "viral_debate",
    },
    {
        "id": "v004",
        "author": "sama",
        "text": "hot take: we'll have AGI before we have reliable self-driving cars. the hard parts of driving are mostly physical and edge-case adversarial. the hard parts of intelligence are mostly solved.",
        "likes": 31000,
        "retweets": 7400,
        "replies": 5600,
        "posted_at": _ago(hours=4, minutes=20),
        "url": "https://twitter.com/sama/status/v004",
        "category": "viral_debate",
    },
    {
        "id": "v005",
        "author": "fchollet",
        "text": "The fact that GPT-4 can write decent code doesn't mean it understands programming. It means the training corpus contained enough code that statistical interpolation produces valid syntax. These are very different things and the conflation is causing real confusion.",
        "likes": 5100,
        "retweets": 1700,
        "replies": 1100,
        "posted_at": _ago(hours=14, minutes=45),
        "url": "https://twitter.com/fchollet/status/v005",
        "category": "viral_debate",
    },
    {
        "id": "v006",
        "author": "scaling01",
        "text": "thread: why I think the next 18 months will see more AI capability progress than the previous 5 years combined. compute is catching up to algorithm improvements. the bottleneck is shifting. 1/",
        "likes": 3800,
        "retweets": 1400,
        "replies": 620,
        "posted_at": _ago(hours=7, minutes=30),
        "url": "https://twitter.com/scaling01/status/v006",
        "category": "viral_debate",
    },
    {
        "id": "v007",
        "author": "gdb",
        "text": "actually I disagree with most AI safety doomerism not because I think it's wrong, but because I think the framing leads to bad interventions. we should focus on alignment research, not policy that slows capabilities at safe labs.",
        "likes": 4600,
        "retweets": 1200,
        "replies": 1500,
        "posted_at": _ago(hours=12, minutes=20),
        "url": "https://twitter.com/gdb/status/v007",
        "category": "viral_debate",
    },

    # ── BENCHMARKS & NUMBERS ────────────────────────────────────────────────
    {
        "id": "b001",
        "author": "_akhaliq",
        "text": "Updated LMSys chatbot arena leaderboard. Claude 4 has taken the #1 spot overall. GPT-5 second. Gemini Ultra 2 third. Full breakdown by category: lmsys.org/arena",
        "likes": 4100,
        "retweets": 1600,
        "replies": 380,
        "posted_at": _ago(hours=2, minutes=0),
        "url": "https://twitter.com/_akhaliq/status/b001",
        "category": "benchmark_numbers",
    },
    {
        "id": "b002",
        "author": "OpenAI",
        "text": "GPT-5 benchmark results: MMLU 92.3% (vs GPT-4's 86.4%), HumanEval 96.1% (vs 67%), MATH 87.4% (vs 52.9%). Full evals: openai.com/gpt-5-evals",
        "likes": 7800,
        "retweets": 2900,
        "replies": 920,
        "posted_at": _ago(hours=3, minutes=15),
        "url": "https://twitter.com/OpenAI/status/b002",
        "category": "benchmark_numbers",
    },
    {
        "id": "b003",
        "author": "AnthropicAI",
        "text": "Claude 4 on SWE-bench Verified: 72.0%. That's 20 points above the previous SOTA. We also score 89.4% on MMLU and 68% on ARC-AGI. Full technical report: anthropic.com/claude4-report",
        "likes": 5300,
        "retweets": 1900,
        "replies": 540,
        "posted_at": _ago(hours=6, minutes=45),
        "url": "https://twitter.com/AnthropicAI/status/b003",
        "category": "benchmark_numbers",
    },
    {
        "id": "b004",
        "author": "rohanpaul_ai",
        "text": "Comparing frontier models on coding (HumanEval): GPT-5: 96.1% | Claude 4: 94.3% | Gemini Ultra 2: 91.8% | Llama 4 70B: 88.2% | Mistral Large 3: 85.7%. Open models are closing the gap fast.",
        "likes": 6200,
        "retweets": 2400,
        "replies": 480,
        "posted_at": _ago(hours=8, minutes=20),
        "url": "https://twitter.com/rohanpaul_ai/status/b004",
        "category": "benchmark_numbers",
    },
    {
        "id": "b005",
        "author": "GoogleDeepMind",
        "text": "Gemini Ultra 2 achieves 90.0% on MMLU, 87.8% on MATH, and 84.1% on HumanEval. Most importantly: 94.4% on MMMU (multimodal understanding) — a new state of the art. Full report: deepmind.google/gemini2-report",
        "likes": 4800,
        "retweets": 1700,
        "replies": 390,
        "posted_at": _ago(hours=5, minutes=50),
        "url": "https://twitter.com/GoogleDeepMind/status/b005",
        "category": "benchmark_numbers",
    },
    {
        "id": "b006",
        "author": "fchollet",
        "text": "ARC-AGI 2 scores: GPT-5: 18%, Claude 4: 21%, Gemini Ultra 2: 16%, o3-mini: 14%, Human average: 98%. These models are not AGI. The benchmark is working exactly as intended.",
        "likes": 8900,
        "retweets": 3300,
        "replies": 1600,
        "posted_at": _ago(hours=16, minutes=0),
        "url": "https://twitter.com/fchollet/status/b006",
        "category": "benchmark_numbers",
    },
]


def get_mock_tweets():
    """Return mock tweets with freshly computed timestamps (always current)."""
    return MOCK_TWEETS
